input {
  syslog {
    port => 5044
    syslog_field => "syslog"
  }
}


output {
  file {
    path => "/var/log/logstash/outputlogs/Syslog-%{+yyyy-MM-dd}.log"
    codec => line { format => "FortiGate: %{message}" }
  }
}